services:
  - type: web
    name: plag-checker-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    workingDir: Backend
    envVars:
      - key: CTAGS_PATH
        value: bin/ctags.exe
