services:
  - type: web
    name: plag-backend
    env: python
    plan: free
    buildCommand: pip install -r Backend/requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:$PORT main:app
    envVars:
      - key: CTAGS_PATH
        value: bin/ctags.exe
    workingDir: Backend
